###
POST http://localhost:3000/auth/api/v1/encomendas/
Content-Type: application/json

{
        "id":"BF01234567810",
        "nome_proprietario":"teste02",
        "contacto":"23834567",
        "endereco":"fazenda",
        "documentos":"SM20051002",
        "status":"vindo"

}
###
GET http://localhost:3000/get/api/v1/encomendas
###
GET http://localhost:3000/search/api/v1/encomendas/entregues
###
GET http://localhost:3000/search/api/v1/encomendas/vindo
###
GET http://localhost:3000/search/api/v1/encomendas/teste02

###
PUT http://localhost:3000/update/api/v1/encomendas/BF0123456789
Content-Type: application/json

{
        "status":"entregue"

}