###
POST http://localhost:3000/correioAPI/api/v1/encomendas/
Content-Type: application/json

{
        "id":"BF0123456786",
        "nome_proprietario":"Mirian Lima",
        "contacto":"1234567",
        "endereco":"Terra Branca",
        "documentos":"SM2000514",
        "status":"vindo"

}
###
POST http://localhost:3000/correioAPI/api/v1/admin
Content-Type: application/json

{
        "nome":"admin",
        "senha":"admin"

}
###
GET http://localhost:3000/correioAPI/api/v1/encomendas
###
GET https://api.warezcdn.com/isd8fusad129ud1ddha0/series/list/1
###
GET http://localhost:3000/correioAPI/api/v1/admin
###
GET http://localhost:3000/correioAPI/api/v1/encomendas/entregues
###
GET http://localhost:3000/correioAPI/api/v1/encomendas/vindo
###
GET http://localhost:3000/correioAPI/api/v1/encomendas/Mirian%20Lima

###
PUT http://localhost:3000/correioAPI/api/v1/encomendas/BF0123456786
Content-Type: application/json

{
        "status":"entregue"

}